### ISSUE TITLE
OSError: PortAudio library not found

### ISSUE THREAD

**Issue by unicodeFun** [CrazyFlyKite/MorseCodePy#4]
Is there a way to build this without PortAudio?  

```
sven@tree:~/Hack/led $ cat morse.py
#!/usr/bin/python

from MorseCodePy import encode

s = encode('goodbye crule world', language='english')
print(s)

sven@tree:~/Hack/led $ make  morse
PYTHONPATH=./py /usr/bin/python morse.py
Traceback (most recent call last):
  File "/home/sven/Hack/led/morse.py", line 3, in <module>
    from MorseCodePy import encode
  File "/home/sven/Hack/led/py/MorseCodePy/__init__.py", line 5, in <module>
    from .play_sounddevice import play_sounddevice
  File "/home/sven/Hack/led/py/MorseCodePy/play_sounddevice.py", line 4, in <module>
    import sounddevice
  File "/home/sven/Hack/led/py/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not fouOSError: PortAudio library not foundnd
make: *** [Makefile:26: morse] Error 1
sven@tree:~/Hack/led $ 
```

**Comment by CrazyFlyKite** [comment]
Hello! And sorry for very long response...

I finally fixed the bug by removing all the audio play functionality. Anyway, no one ever used it or will, because it won't work properly anywhere. Now the library doesn't have any dependencies and **should** work like it should on every device.

Hope you the the library! If you have any other problems or questions, ask me.
